# ============================================================
# Stage 1: Build modules
# ============================================================

FROM maven:3.9.11-eclipse-temurin-21 AS builder

WORKDIR /build

# Copy Maven descriptors first (cache dependencies)
COPY pom.xml .

COPY domain/pom.xml domain/
COPY application/pom.xml application/
COPY infrastructure/pom.xml infrastructure/
COPY launcher/pom.xml launcher/

# Download dependencies
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B dependency:go-offline -DskipTests

# Copy source code
COPY domain/src domain/src
COPY application/src application/src
COPY infrastructure/src infrastructure/src
COPY launcher/src launcher/src

# Copy API contract
COPY api api

# Build launcher and required modules
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B clean package \
    -pl launcher \
    -am \
    -DskipTests


# ============================================================
# Stage 2: Runtime image
# ============================================================

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

RUN addgroup -S developer && \
    adduser -S developer -G developer -u 1001

USER developer

# JPMS application modules
COPY --from=builder /build/domain/target/*.jar /app/
COPY --from=builder /build/application/target/*.jar /app/
COPY --from=builder /build/infrastructure/target/*.jar /app/
COPY --from=builder /build/launcher/target/launcher-*.jar /app/

# Runtime dependencies generated by maven-dependency-plugin
COPY --from=builder /build/launcher/target/lib /app/lib

EXPOSE 8080

ENTRYPOINT ["java", \
    "--module-path", "/app:/app/lib", \
    "--add-opens=java.base/java.lang=ALL-UNNAMED", \
    "-m", "vmp.trade.services.launcher/pl.es8it.vmp.trade.launcher.VmpTradeServicesApplication"]