server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: ${DB_SCHEMA}
    table: schema_version

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}